name: "Set up Nix + Cache"
description: ""

runs:
  using: "composite"
  steps:
      - name: Install
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Add extra cache
        uses: cachix/cachix-action@v10
        with:
          name: kip93
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
          skipPush: true

      - name: Print metadata
        shell: sh
        run: |
          nix-shell -p nix-info --run 'nix-info -m' | sed '/^ *$/d'
          nix-instantiate --eval -E '" - nixpkgs version: `${(import <nixpkgs> {}).lib.version}`"' | sed 's/^"//;s/"$//'
