name: Check code quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - "keymap/**"
      - "QMK"
      - "**/*.nix"
      - ".github/actions/nix/**"
      - ".github/workflows/check.yml"
  workflow_dispatch: {}

jobs:
  nix-format:
    name: "Nix: format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix: format"
        run: |
          nix-build scripts/nix-format.nix | xargs sh -c

  nix-lint:
    name: "Nix: lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix: lint"
        run: |
          nix-build scripts/nix-lint.nix | xargs sh -c

  nix-shellcheck:
    name: "Nix: shellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix: shellcheck"
        run: |
          nix-build scripts/nix-shellcheck.nix | xargs sh -c

  nix-vulnerabilities:
    name: "Nix: vulnerabilities"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix: vulnerabilities"
        run: |
          nix-build scripts/nix-vulnerabilities.nix | xargs sh -c

  nix-logic:
    name: "Nix: logic"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          path: ./repo

      - name: "Nix: set up"
        uses: ./repo/.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix: logic"
        working-directory: ./repo
        run: |
          mkdir -p ../tmp
          nix-build scripts/nix-logic.nix | TMPDIR="$(realpath ../tmp)" xargs sh -c

  qmk-format:
    name: "QMK: format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "QMK: format"
        run: |
          nix-build scripts/qmk-format.nix | xargs sh -c

  qmk-lint:
    name: "QMK: lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Nix: set up"
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "QMK: lint"
        run: |
          nix-build scripts/qmk-lint.nix | xargs sh -c
