name: Release

on:
  push:
    branches: [ main ]

jobs:
  compile-and-release:
    name: Compile & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Print nixpkgs version
        run: |
          nix-instantiate --eval -E '"nixpkgs version: ${(import <nixpkgs> {}).lib.version}"'

      - name: Compile
        run: nix-shell --run compile

      - name: Create tag
        uses: fregante/daily-version-action@v1

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .build/firmware.hex
