name: Release

on:
  push:
    branches: [ main, develop ]
    paths:
      - "keymap/**"
      - "QMK"
      - "shell.nix"
      - ".github/actions/nix/**"
      - ".github/actions/release/**"
      - ".github/workflows/release.yml"
  workflow_dispatch: {}

concurrency:
  group: release

jobs:
  compile-and-release:
    name: Compile & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Nix
        uses: ./.github/actions/nix
        with:
          CACHE_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Compile
        run: |
          nix-shell --pure --run compile

      - name: Cache
        run: |
          nix-build scripts/nix-cache.nix | xargs -I{} sh -c '{} kip93'

      - name: Release
        uses: ./.github/actions/release
